# application-uat.yml
spring:
  datasource:
    mariadb:
      url: jdbc:mariadb://your-host:3306/your-db
      username: youruser
      password: yourpass
      sslCa: /etc/certs/ca.pem
      clientCert: /etc/certs/client-cert.p12
      clientCertPassword: yourkeypass

    postgres:
      url: jdbc:postgresql://uat-pg:5432/mydb
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
 